//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccuracyMetrics) DeepCopyInto(out *AccuracyMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccuracyMetrics.
func (in *AccuracyMetrics) DeepCopy() *AccuracyMetrics {
	if in == nil {
		return nil
	}
	out := new(AccuracyMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlternativeStrategy) DeepCopyInto(out *AlternativeStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlternativeStrategy.
func (in *AlternativeStrategy) DeepCopy() *AlternativeStrategy {
	if in == nil {
		return nil
	}
	out := new(AlternativeStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlternativesSpec) DeepCopyInto(out *AlternativesSpec) {
	*out = *in
	if in.Strategies != nil {
		in, out := &in.Strategies, &out.Strategies
		*out = make([]AlternativeStrategy, len(*in))
		copy(*out, *in)
	}
	if in.GPUTypesToConsider != nil {
		in, out := &in.GPUTypesToConsider, &out.GPUTypesToConsider
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlternativesSpec.
func (in *AlternativesSpec) DeepCopy() *AlternativesSpec {
	if in == nil {
		return nil
	}
	out := new(AlternativesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingContact) DeepCopyInto(out *BillingContact) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingContact.
func (in *BillingContact) DeepCopy() *BillingContact {
	if in == nil {
		return nil
	}
	out := new(BillingContact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetAlert) DeepCopyInto(out *BudgetAlert) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Recipients != nil {
		in, out := &in.Recipients, &out.Recipients
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetAlert.
func (in *BudgetAlert) DeepCopy() *BudgetAlert {
	if in == nil {
		return nil
	}
	out := new(BudgetAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetAlertEvent) DeepCopyInto(out *BudgetAlertEvent) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetAlertEvent.
func (in *BudgetAlertEvent) DeepCopy() *BudgetAlertEvent {
	if in == nil {
		return nil
	}
	out := new(BudgetAlertEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetCurrentPeriod) DeepCopyInto(out *BudgetCurrentPeriod) {
	*out = *in
	in.StartDate.DeepCopyInto(&out.StartDate)
	in.EndDate.DeepCopyInto(&out.EndDate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetCurrentPeriod.
func (in *BudgetCurrentPeriod) DeepCopy() *BudgetCurrentPeriod {
	if in == nil {
		return nil
	}
	out := new(BudgetCurrentPeriod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetEnforcement) DeepCopyInto(out *BudgetEnforcement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetEnforcement.
func (in *BudgetEnforcement) DeepCopy() *BudgetEnforcement {
	if in == nil {
		return nil
	}
	out := new(BudgetEnforcement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetForecast) DeepCopyInto(out *BudgetForecast) {
	*out = *in
	if in.EstimatedExhaustionDate != nil {
		in, out := &in.EstimatedExhaustionDate, &out.EstimatedExhaustionDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetForecast.
func (in *BudgetForecast) DeepCopy() *BudgetForecast {
	if in == nil {
		return nil
	}
	out := new(BudgetForecast)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetLimits) DeepCopyInto(out *BudgetLimits) {
	*out = *in
	if in.GPUTypeHours != nil {
		in, out := &in.GPUTypeHours, &out.GPUTypeHours
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetLimits.
func (in *BudgetLimits) DeepCopy() *BudgetLimits {
	if in == nil {
		return nil
	}
	out := new(BudgetLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetPeriod) DeepCopyInto(out *BudgetPeriod) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetPeriod.
func (in *BudgetPeriod) DeepCopy() *BudgetPeriod {
	if in == nil {
		return nil
	}
	out := new(BudgetPeriod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetPriority) DeepCopyInto(out *BudgetPriority) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetPriority.
func (in *BudgetPriority) DeepCopy() *BudgetPriority {
	if in == nil {
		return nil
	}
	out := new(BudgetPriority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetRollover) DeepCopyInto(out *BudgetRollover) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetRollover.
func (in *BudgetRollover) DeepCopy() *BudgetRollover {
	if in == nil {
		return nil
	}
	out := new(BudgetRollover)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetScope) DeepCopyInto(out *BudgetScope) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetScope.
func (in *BudgetScope) DeepCopy() *BudgetScope {
	if in == nil {
		return nil
	}
	out := new(BudgetScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetSpec) DeepCopyInto(out *BudgetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetSpec.
func (in *BudgetSpec) DeepCopy() *BudgetSpec {
	if in == nil {
		return nil
	}
	out := new(BudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetStatus) DeepCopyInto(out *BudgetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetStatus.
func (in *BudgetStatus) DeepCopy() *BudgetStatus {
	if in == nil {
		return nil
	}
	out := new(BudgetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetUsage) DeepCopyInto(out *BudgetUsage) {
	*out = *in
	if in.GPUTypeHours != nil {
		in, out := &in.GPUTypeHours, &out.GPUTypeHours
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetUsage.
func (in *BudgetUsage) DeepCopy() *BudgetUsage {
	if in == nil {
		return nil
	}
	out := new(BudgetUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetUtilization) DeepCopyInto(out *BudgetUtilization) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetUtilization.
func (in *BudgetUtilization) DeepCopy() *BudgetUtilization {
	if in == nil {
		return nil
	}
	out := new(BudgetUtilization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChargebackAllocationModel) DeepCopyInto(out *ChargebackAllocationModel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChargebackAllocationModel.
func (in *ChargebackAllocationModel) DeepCopy() *ChargebackAllocationModel {
	if in == nil {
		return nil
	}
	out := new(ChargebackAllocationModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChargebackCurrentPeriod) DeepCopyInto(out *ChargebackCurrentPeriod) {
	*out = *in
	if in.CostCenters != nil {
		in, out := &in.CostCenters, &out.CostCenters
		*out = make([]CostCenterStatus, len(*in))
		copy(*out, *in)
	}
	if in.ByResourceType != nil {
		in, out := &in.ByResourceType, &out.ByResourceType
		*out = new(ResourceTypeCosts)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChargebackCurrentPeriod.
func (in *ChargebackCurrentPeriod) DeepCopy() *ChargebackCurrentPeriod {
	if in == nil {
		return nil
	}
	out := new(ChargebackCurrentPeriod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChargebackPeriod) DeepCopyInto(out *ChargebackPeriod) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChargebackPeriod.
func (in *ChargebackPeriod) DeepCopy() *ChargebackPeriod {
	if in == nil {
		return nil
	}
	out := new(ChargebackPeriod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChargebackPricing) DeepCopyInto(out *ChargebackPricing) {
	*out = *in
	if in.GPURates != nil {
		in, out := &in.GPURates, &out.GPURates
		*out = make(map[string]GPURate, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StoragePricing)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkPricing)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChargebackPricing.
func (in *ChargebackPricing) DeepCopy() *ChargebackPricing {
	if in == nil {
		return nil
	}
	out := new(ChargebackPricing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChargebackReportRef) DeepCopyInto(out *ChargebackReportRef) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChargebackReportRef.
func (in *ChargebackReportRef) DeepCopy() *ChargebackReportRef {
	if in == nil {
		return nil
	}
	out := new(ChargebackReportRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChargebackReports) DeepCopyInto(out *ChargebackReports) {
	*out = *in
	if in.Formats != nil {
		in, out := &in.Formats, &out.Formats
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChargebackReports.
func (in *ChargebackReports) DeepCopy() *ChargebackReports {
	if in == nil {
		return nil
	}
	out := new(ChargebackReports)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostCenter) DeepCopyInto(out *CostCenter) {
	*out = *in
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Budget != nil {
		in, out := &in.Budget, &out.Budget
		*out = new(CostCenterBudget)
		**out = **in
	}
	if in.BillingContact != nil {
		in, out := &in.BillingContact, &out.BillingContact
		*out = new(BillingContact)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostCenter.
func (in *CostCenter) DeepCopy() *CostCenter {
	if in == nil {
		return nil
	}
	out := new(CostCenter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostCenterBudget) DeepCopyInto(out *CostCenterBudget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostCenterBudget.
func (in *CostCenterBudget) DeepCopy() *CostCenterBudget {
	if in == nil {
		return nil
	}
	out := new(CostCenterBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostCenterStatus) DeepCopyInto(out *CostCenterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostCenterStatus.
func (in *CostCenterStatus) DeepCopy() *CostCenterStatus {
	if in == nil {
		return nil
	}
	out := new(CostCenterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostEstimationModelSpec) DeepCopyInto(out *CostEstimationModelSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostEstimationModelSpec.
func (in *CostEstimationModelSpec) DeepCopy() *CostEstimationModelSpec {
	if in == nil {
		return nil
	}
	out := new(CostEstimationModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUQuotaSpec) DeepCopyInto(out *GPUQuotaSpec) {
	*out = *in
	if in.AllowedGPUTypes != nil {
		in, out := &in.AllowedGPUTypes, &out.AllowedGPUTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUQuotaSpec.
func (in *GPUQuotaSpec) DeepCopy() *GPUQuotaSpec {
	if in == nil {
		return nil
	}
	out := new(GPUQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURate) DeepCopyInto(out *GPURate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURate.
func (in *GPURate) DeepCopy() *GPURate {
	if in == nil {
		return nil
	}
	out := new(GPURate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaAIJob) DeepCopyInto(out *GryviaAIJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaAIJob.
func (in *GryviaAIJob) DeepCopy() *GryviaAIJob {
	if in == nil {
		return nil
	}
	out := new(GryviaAIJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaAIJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaAIJobDistributedSpec) DeepCopyInto(out *GryviaAIJobDistributedSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaAIJobDistributedSpec.
func (in *GryviaAIJobDistributedSpec) DeepCopy() *GryviaAIJobDistributedSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaAIJobDistributedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaAIJobList) DeepCopyInto(out *GryviaAIJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaAIJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaAIJobList.
func (in *GryviaAIJobList) DeepCopy() *GryviaAIJobList {
	if in == nil {
		return nil
	}
	out := new(GryviaAIJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaAIJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaAIJobSpec) DeepCopyInto(out *GryviaAIJobSpec) {
	*out = *in
	if in.Distributed != nil {
		in, out := &in.Distributed, &out.Distributed
		*out = new(GryviaAIJobDistributedSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaAIJobSpec.
func (in *GryviaAIJobSpec) DeepCopy() *GryviaAIJobSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaAIJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaAIJobStatus) DeepCopyInto(out *GryviaAIJobStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodesAllocated != nil {
		in, out := &in.NodesAllocated, &out.NodesAllocated
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaAIJobStatus.
func (in *GryviaAIJobStatus) DeepCopy() *GryviaAIJobStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaAIJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaBudget) DeepCopyInto(out *GryviaBudget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaBudget.
func (in *GryviaBudget) DeepCopy() *GryviaBudget {
	if in == nil {
		return nil
	}
	out := new(GryviaBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaBudget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaBudgetList) DeepCopyInto(out *GryviaBudgetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaBudget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaBudgetList.
func (in *GryviaBudgetList) DeepCopy() *GryviaBudgetList {
	if in == nil {
		return nil
	}
	out := new(GryviaBudgetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaBudgetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaBudgetSpec) DeepCopyInto(out *GryviaBudgetSpec) {
	*out = *in
	out.Scope = in.Scope
	out.Period = in.Period
	in.Limits.DeepCopyInto(&out.Limits)
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = make([]BudgetAlert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Enforcement != nil {
		in, out := &in.Enforcement, &out.Enforcement
		*out = new(BudgetEnforcement)
		**out = **in
	}
	if in.Rollover != nil {
		in, out := &in.Rollover, &out.Rollover
		*out = new(BudgetRollover)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(BudgetPriority)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaBudgetSpec.
func (in *GryviaBudgetSpec) DeepCopy() *GryviaBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaBudgetStatus) DeepCopyInto(out *GryviaBudgetStatus) {
	*out = *in
	if in.CurrentPeriod != nil {
		in, out := &in.CurrentPeriod, &out.CurrentPeriod
		*out = new(BudgetCurrentPeriod)
		(*in).DeepCopyInto(*out)
	}
	if in.Usage != nil {
		in, out := &in.Usage, &out.Usage
		*out = new(BudgetUsage)
		(*in).DeepCopyInto(*out)
	}
	if in.Utilization != nil {
		in, out := &in.Utilization, &out.Utilization
		*out = new(BudgetUtilization)
		**out = **in
	}
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = make([]BudgetAlertEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Forecast != nil {
		in, out := &in.Forecast, &out.Forecast
		*out = new(BudgetForecast)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaBudgetStatus.
func (in *GryviaBudgetStatus) DeepCopy() *GryviaBudgetStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaBudgetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaChargeback) DeepCopyInto(out *GryviaChargeback) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaChargeback.
func (in *GryviaChargeback) DeepCopy() *GryviaChargeback {
	if in == nil {
		return nil
	}
	out := new(GryviaChargeback)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaChargeback) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaChargebackList) DeepCopyInto(out *GryviaChargebackList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaChargeback, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaChargebackList.
func (in *GryviaChargebackList) DeepCopy() *GryviaChargebackList {
	if in == nil {
		return nil
	}
	out := new(GryviaChargebackList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaChargebackList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaChargebackSpec) DeepCopyInto(out *GryviaChargebackSpec) {
	*out = *in
	out.Period = in.Period
	out.AllocationModel = in.AllocationModel
	in.Pricing.DeepCopyInto(&out.Pricing)
	if in.CostCenters != nil {
		in, out := &in.CostCenters, &out.CostCenters
		*out = make([]CostCenter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Reports != nil {
		in, out := &in.Reports, &out.Reports
		*out = new(ChargebackReports)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaChargebackSpec.
func (in *GryviaChargebackSpec) DeepCopy() *GryviaChargebackSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaChargebackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaChargebackStatus) DeepCopyInto(out *GryviaChargebackStatus) {
	*out = *in
	if in.CurrentPeriod != nil {
		in, out := &in.CurrentPeriod, &out.CurrentPeriod
		*out = new(ChargebackCurrentPeriod)
		(*in).DeepCopyInto(*out)
	}
	if in.LastReport != nil {
		in, out := &in.LastReport, &out.LastReport
		*out = new(ChargebackReportRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaChargebackStatus.
func (in *GryviaChargebackStatus) DeepCopy() *GryviaChargebackStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaChargebackStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaCostPredictor) DeepCopyInto(out *GryviaCostPredictor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaCostPredictor.
func (in *GryviaCostPredictor) DeepCopy() *GryviaCostPredictor {
	if in == nil {
		return nil
	}
	out := new(GryviaCostPredictor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaCostPredictor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaCostPredictorList) DeepCopyInto(out *GryviaCostPredictorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaCostPredictor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaCostPredictorList.
func (in *GryviaCostPredictorList) DeepCopy() *GryviaCostPredictorList {
	if in == nil {
		return nil
	}
	out := new(GryviaCostPredictorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaCostPredictorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaCostPredictorSpec) DeepCopyInto(out *GryviaCostPredictorSpec) {
	*out = *in
	in.HistoricalData.DeepCopyInto(&out.HistoricalData)
	in.Models.DeepCopyInto(&out.Models)
	in.Alternatives.DeepCopyInto(&out.Alternatives)
	out.Integration = in.Integration
	in.Pricing.DeepCopyInto(&out.Pricing)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaCostPredictorSpec.
func (in *GryviaCostPredictorSpec) DeepCopy() *GryviaCostPredictorSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaCostPredictorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaCostPredictorStatus) DeepCopyInto(out *GryviaCostPredictorStatus) {
	*out = *in
	out.PredictionAccuracy = in.PredictionAccuracy
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaCostPredictorStatus.
func (in *GryviaCostPredictorStatus) DeepCopy() *GryviaCostPredictorStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaCostPredictorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaGpuSku) DeepCopyInto(out *GryviaGpuSku) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaGpuSku.
func (in *GryviaGpuSku) DeepCopy() *GryviaGpuSku {
	if in == nil {
		return nil
	}
	out := new(GryviaGpuSku)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaGpuSku) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaGpuSkuList) DeepCopyInto(out *GryviaGpuSkuList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaGpuSku, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaGpuSkuList.
func (in *GryviaGpuSkuList) DeepCopy() *GryviaGpuSkuList {
	if in == nil {
		return nil
	}
	out := new(GryviaGpuSkuList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaGpuSkuList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaGpuSkuSpec) DeepCopyInto(out *GryviaGpuSkuSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaGpuSkuSpec.
func (in *GryviaGpuSkuSpec) DeepCopy() *GryviaGpuSkuSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaGpuSkuSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaInvoice) DeepCopyInto(out *GryviaInvoice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaInvoice.
func (in *GryviaInvoice) DeepCopy() *GryviaInvoice {
	if in == nil {
		return nil
	}
	out := new(GryviaInvoice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaInvoice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaInvoiceList) DeepCopyInto(out *GryviaInvoiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaInvoice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaInvoiceList.
func (in *GryviaInvoiceList) DeepCopy() *GryviaInvoiceList {
	if in == nil {
		return nil
	}
	out := new(GryviaInvoiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaInvoiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaInvoiceSpec) DeepCopyInto(out *GryviaInvoiceSpec) {
	*out = *in
	if in.Lines != nil {
		in, out := &in.Lines, &out.Lines
		*out = make([]InvoiceLine, len(*in))
		copy(*out, *in)
	}
	out.Ledger = in.Ledger
	if in.FinalizedAt != nil {
		in, out := &in.FinalizedAt, &out.FinalizedAt
		*out = (*in).DeepCopy()
	}
	if in.PaidAt != nil {
		in, out := &in.PaidAt, &out.PaidAt
		*out = (*in).DeepCopy()
	}
	if in.VoidedAt != nil {
		in, out := &in.VoidedAt, &out.VoidedAt
		*out = (*in).DeepCopy()
	}
	if in.Payment != nil {
		in, out := &in.Payment, &out.Payment
		*out = new(InvoicePayment)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaInvoiceSpec.
func (in *GryviaInvoiceSpec) DeepCopy() *GryviaInvoiceSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaInvoiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaLedgerEntry) DeepCopyInto(out *GryviaLedgerEntry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaLedgerEntry.
func (in *GryviaLedgerEntry) DeepCopy() *GryviaLedgerEntry {
	if in == nil {
		return nil
	}
	out := new(GryviaLedgerEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaLedgerEntry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaLedgerEntryList) DeepCopyInto(out *GryviaLedgerEntryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaLedgerEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaLedgerEntryList.
func (in *GryviaLedgerEntryList) DeepCopy() *GryviaLedgerEntryList {
	if in == nil {
		return nil
	}
	out := new(GryviaLedgerEntryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaLedgerEntryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaLedgerEntrySpec) DeepCopyInto(out *GryviaLedgerEntrySpec) {
	*out = *in
	out.UsageRecord = in.UsageRecord
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaLedgerEntrySpec.
func (in *GryviaLedgerEntrySpec) DeepCopy() *GryviaLedgerEntrySpec {
	if in == nil {
		return nil
	}
	out := new(GryviaLedgerEntrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaNetworkRate) DeepCopyInto(out *GryviaNetworkRate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaNetworkRate.
func (in *GryviaNetworkRate) DeepCopy() *GryviaNetworkRate {
	if in == nil {
		return nil
	}
	out := new(GryviaNetworkRate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaNetworkRate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaNetworkRateList) DeepCopyInto(out *GryviaNetworkRateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaNetworkRate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaNetworkRateList.
func (in *GryviaNetworkRateList) DeepCopy() *GryviaNetworkRateList {
	if in == nil {
		return nil
	}
	out := new(GryviaNetworkRateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaNetworkRateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaNetworkRateSpec) DeepCopyInto(out *GryviaNetworkRateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaNetworkRateSpec.
func (in *GryviaNetworkRateSpec) DeepCopy() *GryviaNetworkRateSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaNetworkRateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaNetworkUsageRecord) DeepCopyInto(out *GryviaNetworkUsageRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaNetworkUsageRecord.
func (in *GryviaNetworkUsageRecord) DeepCopy() *GryviaNetworkUsageRecord {
	if in == nil {
		return nil
	}
	out := new(GryviaNetworkUsageRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaNetworkUsageRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaNetworkUsageRecordList) DeepCopyInto(out *GryviaNetworkUsageRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaNetworkUsageRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaNetworkUsageRecordList.
func (in *GryviaNetworkUsageRecordList) DeepCopy() *GryviaNetworkUsageRecordList {
	if in == nil {
		return nil
	}
	out := new(GryviaNetworkUsageRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaNetworkUsageRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaNetworkUsageRecordSpec) DeepCopyInto(out *GryviaNetworkUsageRecordSpec) {
	*out = *in
	in.Hour.DeepCopyInto(&out.Hour)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaNetworkUsageRecordSpec.
func (in *GryviaNetworkUsageRecordSpec) DeepCopy() *GryviaNetworkUsageRecordSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaNetworkUsageRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaQuota) DeepCopyInto(out *GryviaQuota) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaQuota.
func (in *GryviaQuota) DeepCopy() *GryviaQuota {
	if in == nil {
		return nil
	}
	out := new(GryviaQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaQuota) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaQuotaList) DeepCopyInto(out *GryviaQuotaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaQuota, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaQuotaList.
func (in *GryviaQuotaList) DeepCopy() *GryviaQuotaList {
	if in == nil {
		return nil
	}
	out := new(GryviaQuotaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaQuotaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaQuotaSpec) DeepCopyInto(out *GryviaQuotaSpec) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.GPUQuota.DeepCopyInto(&out.GPUQuota)
	if in.Budget != nil {
		in, out := &in.Budget, &out.Budget
		*out = new(BudgetSpec)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TokensPerDay != nil {
		in, out := &in.TokensPerDay, &out.TokensPerDay
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaQuotaSpec.
func (in *GryviaQuotaSpec) DeepCopy() *GryviaQuotaSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaQuotaStatus) DeepCopyInto(out *GryviaQuotaStatus) {
	*out = *in
	out.CurrentUsage = in.CurrentUsage
	if in.BudgetStatus != nil {
		in, out := &in.BudgetStatus, &out.BudgetStatus
		*out = new(BudgetStatus)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaQuotaStatus.
func (in *GryviaQuotaStatus) DeepCopy() *GryviaQuotaStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaQuotaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaReservation) DeepCopyInto(out *GryviaReservation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaReservation.
func (in *GryviaReservation) DeepCopy() *GryviaReservation {
	if in == nil {
		return nil
	}
	out := new(GryviaReservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaReservation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaReservationList) DeepCopyInto(out *GryviaReservationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaReservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaReservationList.
func (in *GryviaReservationList) DeepCopy() *GryviaReservationList {
	if in == nil {
		return nil
	}
	out := new(GryviaReservationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaReservationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaReservationSpec) DeepCopyInto(out *GryviaReservationSpec) {
	*out = *in
	out.Owner = in.Owner
	in.Resources.DeepCopyInto(&out.Resources)
	in.Schedule.DeepCopyInto(&out.Schedule)
	if in.Guarantees != nil {
		in, out := &in.Guarantees, &out.Guarantees
		*out = new(ReservationGuarantees)
		(*in).DeepCopyInto(*out)
	}
	if in.Billing != nil {
		in, out := &in.Billing, &out.Billing
		*out = new(ReservationBilling)
		**out = **in
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = new(ReservationNotifications)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaReservationSpec.
func (in *GryviaReservationSpec) DeepCopy() *GryviaReservationSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaReservationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaReservationStatus) DeepCopyInto(out *GryviaReservationStatus) {
	*out = *in
	if in.ActualStartTime != nil {
		in, out := &in.ActualStartTime, &out.ActualStartTime
		*out = (*in).DeepCopy()
	}
	if in.ActualEndTime != nil {
		in, out := &in.ActualEndTime, &out.ActualEndTime
		*out = (*in).DeepCopy()
	}
	if in.AllocatedNodes != nil {
		in, out := &in.AllocatedNodes, &out.AllocatedNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UtilizationMetrics != nil {
		in, out := &in.UtilizationMetrics, &out.UtilizationMetrics
		*out = new(ReservationUtilization)
		**out = **in
	}
	if in.Cost != nil {
		in, out := &in.Cost, &out.Cost
		*out = new(ReservationCost)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaReservationStatus.
func (in *GryviaReservationStatus) DeepCopy() *GryviaReservationStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaReservationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaTenant) DeepCopyInto(out *GryviaTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaTenant.
func (in *GryviaTenant) DeepCopy() *GryviaTenant {
	if in == nil {
		return nil
	}
	out := new(GryviaTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaTenantList) DeepCopyInto(out *GryviaTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaTenantList.
func (in *GryviaTenantList) DeepCopy() *GryviaTenantList {
	if in == nil {
		return nil
	}
	out := new(GryviaTenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaTenantSpec) DeepCopyInto(out *GryviaTenantSpec) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]TenantMember, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Quotas != nil {
		in, out := &in.Quotas, &out.Quotas
		*out = new(TenantQuotas)
		(*in).DeepCopyInto(*out)
	}
	if in.Priorities != nil {
		in, out := &in.Priorities, &out.Priorities
		*out = new(TenantPriorities)
		**out = **in
	}
	if in.NetworkPolicy != nil {
		in, out := &in.NetworkPolicy, &out.NetworkPolicy
		*out = new(TenantNetworkPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.StorageQuotas != nil {
		in, out := &in.StorageQuotas, &out.StorageQuotas
		*out = new(TenantStorageQuotas)
		**out = **in
	}
	if in.JobDefaults != nil {
		in, out := &in.JobDefaults, &out.JobDefaults
		*out = new(TenantJobDefaults)
		**out = **in
	}
	if in.Billing != nil {
		in, out := &in.Billing, &out.Billing
		*out = new(TenantBilling)
		**out = **in
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = new(TenantNotifications)
		(*in).DeepCopyInto(*out)
	}
	if in.Governance != nil {
		in, out := &in.Governance, &out.Governance
		*out = new(TenantGovernance)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedSkus != nil {
		in, out := &in.AllowedSkus, &out.AllowedSkus
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OIDCGroups != nil {
		in, out := &in.OIDCGroups, &out.OIDCGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaTenantSpec.
func (in *GryviaTenantSpec) DeepCopy() *GryviaTenantSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaTenantStatus) DeepCopyInto(out *GryviaTenantStatus) {
	*out = *in
	if in.CurrentUsage != nil {
		in, out := &in.CurrentUsage, &out.CurrentUsage
		*out = new(TenantCurrentUsage)
		**out = **in
	}
	if in.QuotaUtilization != nil {
		in, out := &in.QuotaUtilization, &out.QuotaUtilization
		*out = new(TenantQuotaUtilization)
		**out = **in
	}
	if in.NamespacesManaged != nil {
		in, out := &in.NamespacesManaged, &out.NamespacesManaged
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaTenantStatus.
func (in *GryviaTenantStatus) DeepCopy() *GryviaTenantStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaTenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaUsageRecord) DeepCopyInto(out *GryviaUsageRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaUsageRecord.
func (in *GryviaUsageRecord) DeepCopy() *GryviaUsageRecord {
	if in == nil {
		return nil
	}
	out := new(GryviaUsageRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaUsageRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaUsageRecordList) DeepCopyInto(out *GryviaUsageRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaUsageRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaUsageRecordList.
func (in *GryviaUsageRecordList) DeepCopy() *GryviaUsageRecordList {
	if in == nil {
		return nil
	}
	out := new(GryviaUsageRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaUsageRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaUsageRecordSpec) DeepCopyInto(out *GryviaUsageRecordSpec) {
	*out = *in
	in.Start.DeepCopyInto(&out.Start)
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaUsageRecordSpec.
func (in *GryviaUsageRecordSpec) DeepCopy() *GryviaUsageRecordSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaUsageRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HistoricalDataSpec) DeepCopyInto(out *HistoricalDataSpec) {
	*out = *in
	if in.SimilarityFactors != nil {
		in, out := &in.SimilarityFactors, &out.SimilarityFactors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HistoricalDataSpec.
func (in *HistoricalDataSpec) DeepCopy() *HistoricalDataSpec {
	if in == nil {
		return nil
	}
	out := new(HistoricalDataSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationSpec) DeepCopyInto(out *IntegrationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationSpec.
func (in *IntegrationSpec) DeepCopy() *IntegrationSpec {
	if in == nil {
		return nil
	}
	out := new(IntegrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoiceLedgerRange) DeepCopyInto(out *InvoiceLedgerRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoiceLedgerRange.
func (in *InvoiceLedgerRange) DeepCopy() *InvoiceLedgerRange {
	if in == nil {
		return nil
	}
	out := new(InvoiceLedgerRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoiceLine) DeepCopyInto(out *InvoiceLine) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoiceLine.
func (in *InvoiceLine) DeepCopy() *InvoiceLine {
	if in == nil {
		return nil
	}
	out := new(InvoiceLine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoicePayment) DeepCopyInto(out *InvoicePayment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoicePayment.
func (in *InvoicePayment) DeepCopy() *InvoicePayment {
	if in == nil {
		return nil
	}
	out := new(InvoicePayment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPricing) DeepCopyInto(out *NetworkPricing) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPricing.
func (in *NetworkPricing) DeepCopy() *NetworkPricing {
	if in == nil {
		return nil
	}
	out := new(NetworkPricing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSpec) DeepCopyInto(out *NetworkSpec) {
	*out = *in
	if in.MaxEgressMbps != nil {
		in, out := &in.MaxEgressMbps, &out.MaxEgressMbps
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSpec.
func (in *NetworkSpec) DeepCopy() *NetworkSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictionAccuracyStatus) DeepCopyInto(out *PredictionAccuracyStatus) {
	*out = *in
	out.TimeEstimate = in.TimeEstimate
	out.CostEstimate = in.CostEstimate
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictionAccuracyStatus.
func (in *PredictionAccuracyStatus) DeepCopy() *PredictionAccuracyStatus {
	if in == nil {
		return nil
	}
	out := new(PredictionAccuracyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictionModelsSpec) DeepCopyInto(out *PredictionModelsSpec) {
	*out = *in
	in.TrainingTime.DeepCopyInto(&out.TrainingTime)
	out.CostEstimation = in.CostEstimation
	out.QueueTime = in.QueueTime
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictionModelsSpec.
func (in *PredictionModelsSpec) DeepCopy() *PredictionModelsSpec {
	if in == nil {
		return nil
	}
	out := new(PredictionModelsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PricingSpec) DeepCopyInto(out *PricingSpec) {
	*out = *in
	if in.PerGpuHour != nil {
		in, out := &in.PerGpuHour, &out.PerGpuHour
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PricingSpec.
func (in *PricingSpec) DeepCopy() *PricingSpec {
	if in == nil {
		return nil
	}
	out := new(PricingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueTimeModelSpec) DeepCopyInto(out *QueueTimeModelSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueTimeModelSpec.
func (in *QueueTimeModelSpec) DeepCopy() *QueueTimeModelSpec {
	if in == nil {
		return nil
	}
	out := new(QueueTimeModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaUsage) DeepCopyInto(out *QuotaUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaUsage.
func (in *QuotaUsage) DeepCopy() *QuotaUsage {
	if in == nil {
		return nil
	}
	out := new(QuotaUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationBilling) DeepCopyInto(out *ReservationBilling) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationBilling.
func (in *ReservationBilling) DeepCopy() *ReservationBilling {
	if in == nil {
		return nil
	}
	out := new(ReservationBilling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationCost) DeepCopyInto(out *ReservationCost) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationCost.
func (in *ReservationCost) DeepCopy() *ReservationCost {
	if in == nil {
		return nil
	}
	out := new(ReservationCost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationGuarantees) DeepCopyInto(out *ReservationGuarantees) {
	*out = *in
	if in.SLA != nil {
		in, out := &in.SLA, &out.SLA
		*out = new(ReservationSLA)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationGuarantees.
func (in *ReservationGuarantees) DeepCopy() *ReservationGuarantees {
	if in == nil {
		return nil
	}
	out := new(ReservationGuarantees)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationNotifications) DeepCopyInto(out *ReservationNotifications) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationNotifications.
func (in *ReservationNotifications) DeepCopy() *ReservationNotifications {
	if in == nil {
		return nil
	}
	out := new(ReservationNotifications)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationOwner) DeepCopyInto(out *ReservationOwner) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationOwner.
func (in *ReservationOwner) DeepCopy() *ReservationOwner {
	if in == nil {
		return nil
	}
	out := new(ReservationOwner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationRecurrence) DeepCopyInto(out *ReservationRecurrence) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationRecurrence.
func (in *ReservationRecurrence) DeepCopy() *ReservationRecurrence {
	if in == nil {
		return nil
	}
	out := new(ReservationRecurrence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationResources) DeepCopyInto(out *ReservationResources) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationResources.
func (in *ReservationResources) DeepCopy() *ReservationResources {
	if in == nil {
		return nil
	}
	out := new(ReservationResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationSLA) DeepCopyInto(out *ReservationSLA) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationSLA.
func (in *ReservationSLA) DeepCopy() *ReservationSLA {
	if in == nil {
		return nil
	}
	out := new(ReservationSLA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationSchedule) DeepCopyInto(out *ReservationSchedule) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.Recurrence != nil {
		in, out := &in.Recurrence, &out.Recurrence
		*out = new(ReservationRecurrence)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationSchedule.
func (in *ReservationSchedule) DeepCopy() *ReservationSchedule {
	if in == nil {
		return nil
	}
	out := new(ReservationSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationUtilization) DeepCopyInto(out *ReservationUtilization) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationUtilization.
func (in *ReservationUtilization) DeepCopy() *ReservationUtilization {
	if in == nil {
		return nil
	}
	out := new(ReservationUtilization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceTypeCosts) DeepCopyInto(out *ResourceTypeCosts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceTypeCosts.
func (in *ResourceTypeCosts) DeepCopy() *ResourceTypeCosts {
	if in == nil {
		return nil
	}
	out := new(ResourceTypeCosts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePricing) DeepCopyInto(out *StoragePricing) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePricing.
func (in *StoragePricing) DeepCopy() *StoragePricing {
	if in == nil {
		return nil
	}
	out := new(StoragePricing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantBilling) DeepCopyInto(out *TenantBilling) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantBilling.
func (in *TenantBilling) DeepCopy() *TenantBilling {
	if in == nil {
		return nil
	}
	out := new(TenantBilling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantCostQuota) DeepCopyInto(out *TenantCostQuota) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantCostQuota.
func (in *TenantCostQuota) DeepCopy() *TenantCostQuota {
	if in == nil {
		return nil
	}
	out := new(TenantCostQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantCurrentUsage) DeepCopyInto(out *TenantCurrentUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantCurrentUsage.
func (in *TenantCurrentUsage) DeepCopy() *TenantCurrentUsage {
	if in == nil {
		return nil
	}
	out := new(TenantCurrentUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantGPUHoursQuota) DeepCopyInto(out *TenantGPUHoursQuota) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantGPUHoursQuota.
func (in *TenantGPUHoursQuota) DeepCopy() *TenantGPUHoursQuota {
	if in == nil {
		return nil
	}
	out := new(TenantGPUHoursQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantGPUTypeQuota) DeepCopyInto(out *TenantGPUTypeQuota) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantGPUTypeQuota.
func (in *TenantGPUTypeQuota) DeepCopy() *TenantGPUTypeQuota {
	if in == nil {
		return nil
	}
	out := new(TenantGPUTypeQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantGovernance) DeepCopyInto(out *TenantGovernance) {
	*out = *in
	if in.ComplianceRequirements != nil {
		in, out := &in.ComplianceRequirements, &out.ComplianceRequirements
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantGovernance.
func (in *TenantGovernance) DeepCopy() *TenantGovernance {
	if in == nil {
		return nil
	}
	out := new(TenantGovernance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantJobDefaults) DeepCopyInto(out *TenantJobDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantJobDefaults.
func (in *TenantJobDefaults) DeepCopy() *TenantJobDefaults {
	if in == nil {
		return nil
	}
	out := new(TenantJobDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantMember) DeepCopyInto(out *TenantMember) {
	*out = *in
	if in.JoinedAt != nil {
		in, out := &in.JoinedAt, &out.JoinedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantMember.
func (in *TenantMember) DeepCopy() *TenantMember {
	if in == nil {
		return nil
	}
	out := new(TenantMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantNetworkPolicy) DeepCopyInto(out *TenantNetworkPolicy) {
	*out = *in
	if in.AllowedTenants != nil {
		in, out := &in.AllowedTenants, &out.AllowedTenants
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantNetworkPolicy.
func (in *TenantNetworkPolicy) DeepCopy() *TenantNetworkPolicy {
	if in == nil {
		return nil
	}
	out := new(TenantNetworkPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantNotifications) DeepCopyInto(out *TenantNotifications) {
	*out = *in
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(TenantSlackConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantNotifications.
func (in *TenantNotifications) DeepCopy() *TenantNotifications {
	if in == nil {
		return nil
	}
	out := new(TenantNotifications)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantPriorities) DeepCopyInto(out *TenantPriorities) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantPriorities.
func (in *TenantPriorities) DeepCopy() *TenantPriorities {
	if in == nil {
		return nil
	}
	out := new(TenantPriorities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantQuotaUtilization) DeepCopyInto(out *TenantQuotaUtilization) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantQuotaUtilization.
func (in *TenantQuotaUtilization) DeepCopy() *TenantQuotaUtilization {
	if in == nil {
		return nil
	}
	out := new(TenantQuotaUtilization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantQuotas) DeepCopyInto(out *TenantQuotas) {
	*out = *in
	if in.GPUHours != nil {
		in, out := &in.GPUHours, &out.GPUHours
		*out = new(TenantGPUHoursQuota)
		**out = **in
	}
	if in.CostUSD != nil {
		in, out := &in.CostUSD, &out.CostUSD
		*out = new(TenantCostQuota)
		**out = **in
	}
	if in.PerGPUType != nil {
		in, out := &in.PerGPUType, &out.PerGPUType
		*out = make(map[string]TenantGPUTypeQuota, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantQuotas.
func (in *TenantQuotas) DeepCopy() *TenantQuotas {
	if in == nil {
		return nil
	}
	out := new(TenantQuotas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantSlackConfig) DeepCopyInto(out *TenantSlackConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantSlackConfig.
func (in *TenantSlackConfig) DeepCopy() *TenantSlackConfig {
	if in == nil {
		return nil
	}
	out := new(TenantSlackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantStorageQuotas) DeepCopyInto(out *TenantStorageQuotas) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantStorageQuotas.
func (in *TenantStorageQuotas) DeepCopy() *TenantStorageQuotas {
	if in == nil {
		return nil
	}
	out := new(TenantStorageQuotas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingTimeModelSpec) DeepCopyInto(out *TrainingTimeModelSpec) {
	*out = *in
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingTimeModelSpec.
func (in *TrainingTimeModelSpec) DeepCopy() *TrainingTimeModelSpec {
	if in == nil {
		return nil
	}
	out := new(TrainingTimeModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsageRecordRef) DeepCopyInto(out *UsageRecordRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsageRecordRef.
func (in *UsageRecordRef) DeepCopy() *UsageRecordRef {
	if in == nil {
		return nil
	}
	out := new(UsageRecordRef)
	in.DeepCopyInto(out)
	return out
}
